import './globals.css';
import { Inter, Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const robato = Roboto({ subsets: ['latin'], weight: ['400', '700'] });
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import Providers from './redux/provider';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robato.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
